categories:
  - title: ":rocket: Features"
    labels:
      - enhancement
      - feature
      - feat
  - title: ":beetle: Fixes"
    labels:
      - fix
      - bugfix
      - bug
  - title: ":package: Dependencies"
    labels:
      - dependencies
template: |
  ## What’s Changed

  $CHANGES
