repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: [--branch, dev, --branch, master, --branch, rc]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - --ignore-words=codespell.txt
          - --quiet-level=2
        exclude_types: [json]
        exclude: tests/fixtures/home-assistant.io|tests/resources/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
        args: [--fix]
        files: ^((custom_components/ha_fritzprofiles|tests)/.+)?[^/]+\.(py|pyi)$
      - id: ruff-format
        files: ^((custom_components/ha_fritzprofiles|tests)/.+)?[^/]+\.(py|pyi)$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
  - repo: https://github.com/cdce8p/python-typing-update
    rev: v0.6.0
    hooks:
      # Run `python-typing-update` hook manually from time to time
      # to update python typing syntax.
      # Will require manual work, before submitting changes!
      # prek run --hook-stage manual python-typing-update --all-files
      - id: python-typing-update
        stages: [manual]
        args:
          - --py311-plus
          - --force
          - --keep-updates
        files: ^(custom_components/ha_fritzprofiles|tests)/.+\.py$
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.6.2
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.6.2
          - prettier-plugin-sort-json@4.1.1
