default_config:

logger:
  default: info
  logs:
    custom_components.https://github.com/mithomas/ha-fritzprofiles: debug
# If you need to debug uncommment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:
